const express = require("express");
const bcrypt = require("bcryptjs");
const db = require("../db/db");

const router = express.Router();

router.get("/login", (req, res) => {
  if (req.session && req.session.userId) {
    return res.redirect("/dashboard");
  }
  res.render("login", { error: null });
});

router.post("/login", async (req, res, next) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.render("login", { error: "Please enter your email and password." });
  }

  try {
    const result = await db.query("SELECT * FROM users WHERE email = $1", [email.trim().toLowerCase()]);
    const user = result.rows[0];

    if (!user || !user.password_hash || !bcrypt.compareSync(password, user.password_hash)) {
      return res.render("login", { error: "Incorrect email or password." });
    }

    if (user.status === "invited") {
      return res.render("login", {
        error: "This account hasn't been set up yet - use your invite link to create a password first.",
      });
    }

    if (user.status === "deactivated") {
      return res.render("login", { error: "This account has been deactivated. Contact your team admin." });
    }

    req.session.userId = user.id;
    req.session.userName = user.name;
    req.session.userEmail = user.email;
    req.session.isAdmin = user.is_admin;
    res.redirect("/dashboard");
  } catch (err) {
    next(err);
  }
});

router.post("/logout", (req, res) => {
  req.session.destroy(() => {
    res.redirect("/login");
  });
});

// --- Invite-based signup (link generated by an admin on the Team page) ---

router.get("/signup/:token", async (req, res, next) => {
  try {
    const result = await db.query(
      "SELECT * FROM users WHERE invite_token = $1 AND status = 'invited'",
      [req.params.token]
    );
    const invited = result.rows[0];

    if (!invited || new Date(invited.invite_token_expires_at) < new Date()) {
      return res.render("signup", { invalid: true, invited: null, error: null });
    }

    res.render("signup", { invalid: false, invited, error: null });
  } catch (err) {
    next(err);
  }
});

router.post("/signup/:token", async (req, res, next) => {
  const { name, password, confirmPassword } = req.body;

  try {
    const result = await db.query(
      "SELECT * FROM users WHERE invite_token = $1 AND status = 'invited'",
      [req.params.token]
    );
    const invited = result.rows[0];

    if (!invited || new Date(invited.invite_token_expires_at) < new Date()) {
      return res.render("signup", { invalid: true, invited: null, error: null });
    }

    if (!name || !name.trim()) {
      return res.render("signup", { invalid: false, invited, error: "Please enter your name." });
    }
    if (!password || password.length < 8) {
      return res.render("signup", { invalid: false, invited, error: "Password must be at least 8 characters." });
    }
    if (password !== confirmPassword) {
      return res.render("signup", { invalid: false, invited, error: "Passwords don't match." });
    }

    const hash = bcrypt.hashSync(password, 10);
    await db.query(
      `UPDATE users
       SET name = $1, password_hash = $2, status = 'active', invite_token = NULL, invite_token_expires_at = NULL
       WHERE id = $3`,
      [name.trim(), hash, invited.id]
    );

    req.session.userId = invited.id;
    req.session.userName = name.trim();
    req.session.userEmail = invited.email;
    req.session.isAdmin = invited.is_admin;
    res.redirect("/dashboard");
  } catch (err) {
    next(err);
  }
});

module.exports = router;
